export const PROFILE = {
  name: 'Harshita Guduru',
  title: 'Full-Stack Engineer & ML Researcher',
  tagline: 'Software engineer with expertise in full-stack development, machine learning, and blockchain — with a published research record in deep learning.',
  location: 'Southfield, Michigan, USA',

  contact: {
    email: 'guduruharshita2001@gmail.com',
    phone: '947.240.5093',
    linkedin: 'https://linkedin.com/in/guduruharshita',
    linkedinLabel: 'linkedin.com/in/guduruharshita',
    github: 'https://github.com/guduruharshita',
    githubLabel: 'github.com/guduruharshita',
  },

  experience: [
    {
      role: 'Graduate Research Assistant',
      company: 'Lawrence Technological University',
      location: 'Southfield, MI',
      period: 'Dec 2024 – Present',
      type: 'Research',
      bullets: [
        'Designed and trained a hybrid CNN-LSTM deep learning model for seismic event prediction and synthetic seismogram generation across 10,000+ seismic records.',
        'Achieved 84% classification accuracy — published in the American Journal of Civil Engineering, October 2025.',
        'Developed Python data pipelines using NumPy and Pandas for preprocessing large-scale seismic datasets.',
        'Collaborated with civil engineering faculty to bridge ML research with structural safety applications.',
      ],
      tags: ['TensorFlow', 'Keras', 'CNN-LSTM', 'Python', 'NumPy', 'Pandas', 'Deep Learning'],
    },
    {
      role: 'Associate Software Engineer',
      company: 'Genesis Tech Solutions',
      location: 'Hyderabad, India',
      period: 'May 2023 – Nov 2023',
      type: 'Full-Time',
      bullets: [
        'Built and shipped a full-stack e-learning platform using React.js and Spring Boot serving 1,000+ active users.',
        'Reduced page load time by 30% through component-level code splitting, lazy loading, and API response caching.',
        'Implemented JWT-based authentication with role-based access control (RBAC) for student, instructor, and admin roles.',
        'Designed and managed PostgreSQL schema including user management, course content, and progress tracking tables.',
      ],
      tags: ['React.js', 'Spring Boot', 'PostgreSQL', 'JWT', 'RBAC', 'Java', 'REST APIs'],
    },
  ],

  education: [
    {
      degree: 'M.S. Computer Science',
      school: 'Lawrence Technological University',
      location: 'Southfield, MI',
      period: 'Jan 2024 – May 2026',
      courses: ['Machine Learning', 'Deep Learning', 'Distributed Systems', 'Cloud Computing', 'Data Mining', 'Algorithms'],
    },
    {
      degree: 'B.Tech Computer Science',
      school: 'JNTU Hyderabad',
      location: 'Hyderabad, India',
      period: 'Sep 2019 – May 2023',
      courses: ['Data Structures', 'OOP', 'DBMS', 'Computer Networks', 'Cyber Security', 'Web Development'],
    },
  ],

  projects: [
    {
      title: 'DiscoveryAI',
      subtitle: 'AI-Powered Project Discovery Platform',
      category: 'Full-Stack',
      icon: '🤖',
      period: '2024',
      description: 'Production-ready AI platform that turns natural language into project discovery. FastAPI async backend streams OpenAI responses in real-time, persists query history in PostgreSQL, and serves a React 18 + TypeScript frontend with Vite.',
      highlights: [
        'FastAPI async backend with streaming OpenAI endpoint — responses appear token-by-token in the UI',
        'SQLModel ORM with PostgreSQL persistence for query history; pydantic-settings for 12-factor config',
        'React 18 + TypeScript strict mode + Vite frontend with custom hooks and Tailwind CSS 3',
        'GitHub Actions CI: ruff lint + pytest for API, tsc typecheck + Vite build for frontend',
        'Docker multi-stage build with non-root user; Dockerfile separates dev and production images',
      ],
      tags: ['FastAPI', 'React 18', 'OpenAI API', 'PostgreSQL', 'SQLModel', 'TypeScript', 'Vite', 'Docker'],
      github: 'https://github.com/guduruharshita/Digital-Project-Discovery-AI-Platform',
    },
    {
      title: 'AuthChain',
      subtitle: 'EIP-191 Blockchain Authentication System',
      category: 'Blockchain',
      icon: '🔐',
      period: '2024',
      description: 'Passwordless authentication using Ethereum wallet signatures. The Solidity smart contract (Ownable, Pausable, ReentrancyGuard via OpenZeppelin v5) records access events on-chain; the TypeScript backend issues JWTs after verifying EIP-191 personal_sign signatures.',
      highlights: [
        'Solidity 0.8.24 smart contract with OpenZeppelin v5 — Ownable, Pausable, ReentrancyGuard, 23 Hardhat + Chai tests',
        'EIP-191 personal_sign flow: nonce challenge → MetaMask signature → ethers.js v6 verifyMessage() → JWT issuance',
        'TypeScript/Node.js backend with better-sqlite3 WAL mode; nonce table prevents replay attacks',
        'React 18 + ethers.js v6 frontend: MetaMask detection, wallet connect, nonce-fetch, sign, and login flow',
        'GitHub Actions CI: solhint + Hardhat tests for contracts, tsc + ESLint for frontend',
      ],
      tags: ['Solidity', 'Ethereum', 'EIP-191', 'ethers.js v6', 'Hardhat', 'OpenZeppelin', 'TypeScript', 'JWT'],
      github: 'https://github.com/guduruharshita/Blockchain-base-Authentication-System',
    },
    {
      title: 'CNN-LSTM Seismic Research',
      subtitle: 'Hybrid Deep Learning for Earthquake Prediction',
      category: 'ML Research',
      icon: '🌍',
      period: '2024 – 2025',
      description: 'Published research: hybrid CNN-LSTM architecture for seismic event classification and synthetic seismogram generation. SMOTE-balanced training on 10,000+ records; Ricker wavelet generator for synthetic augmentation. 84% classification accuracy, peer-reviewed October 2025.',
      highlights: [
        'Conv1D → MaxPool → BatchNorm → LSTM → Dense pipeline; L2 regularisation and Dropout prevent overfitting',
        'SMOTE applied to address severe class imbalance in the seismic record dataset',
        'Ricker wavelet seismogram generator produces frequency-controlled synthetic waveforms for data augmentation',
        'MinMaxScaler preprocessing with sliding-window sequence builder for temporal feature extraction',
        'Published in American Journal of Civil Engineering, Vol. 13, Issue 5, October 2025',
      ],
      tags: ['TensorFlow', 'Keras', 'CNN-LSTM', 'SMOTE', 'Python', 'NumPy', 'Pandas', 'Deep Learning'],
      github: 'https://github.com/guduruharshita/Earthquake-Prediction-and-Synthetic-Seismogram-Generation-Using-Hybrid-CNN-LSTM-Model',
      publication: 'https://www.sciencepg.com/article/10.11648/j.ajce.20251305.14',
    },
    {
      title: 'Twitter/X Analytics Engine',
      subtitle: 'Social Media Engagement Prediction with ML',
      category: 'ML',
      icon: '📊',
      period: '2024',
      description: 'Multi-model ensemble analyzing 100,000+ tweets to predict engagement. XGBoost regressor (R²=0.777) combined with a PyTorch neural network and Facebook Prophet time-series forecasting, exposed via a FastAPI inference API.',
      highlights: [
        'Feature engineering: cyclical hour encoding (sin/cos), rolling user aggregates, reply/retweet/quote ratios',
        'XGBoost regressor with StandardScaler — R²=0.777 on engagement score prediction',
        'PyTorch EngagementNN (3-layer MLP) trained end-to-end for engagement classification',
        'Facebook Prophet for time-series forecasting of trending topic cycles with weekly/daily seasonality',
        'FastAPI inference API with create_app() factory; 13 pytest tests covering all models and endpoints',
      ],
      tags: ['XGBoost', 'PyTorch', 'Prophet', 'FastAPI', 'Python', 'Scikit-learn', 'Pandas', 'Feature Engineering'],
      github: 'https://github.com/guduruharshita/twitter-user-timeline-analytics-engagement-prediction-system',
    },
    {
      title: 'Graph Algorithm Library',
      subtitle: 'Graph Algorithms + FastAPI REST Service',
      category: 'Algorithms',
      icon: '🕸️',
      period: '2024',
      description: 'Production-ready graph algorithm library with a REST API. Pure Python implementation of 9 algorithms — BFS, DFS, Dijkstra, Bellman-Ford, cycle detection, topological sort, and Kosaraju SCC — exposed via a FastAPI service with Pydantic-validated endpoints.',
      highlights: [
        'Weighted adjacency-list Graph class with from_edge_list factory; zero non-standard runtime dependencies in core',
        'Dijkstra O((V+E)logV) via heapq; Bellman-Ford with negative-cycle detection; path reconstruction',
        'Kahn\'s BFS topological sort; Kosaraju two-pass DFS + transpose for strongly connected components',
        'FastAPI REST: POST /traverse, /shortest-path, /analyze — all with Pydantic v2 schemas',
        '33 pytest tests covering traversal, shortest path, analysis, and API endpoints',
      ],
      tags: ['Python', 'FastAPI', 'Pydantic', 'BFS', 'DFS', 'Dijkstra', 'Kosaraju SCC', 'Algorithms'],
      github: 'https://github.com/guduruharshita/Graph-traversal-Algorithm',
    },
    {
      title: 'Disaster Events Database',
      subtitle: 'Natural Disaster REST API & Analytics Platform',
      category: 'Full-Stack',
      icon: '🌩️',
      period: '2024',
      description: 'Production REST API backed by a normalized 7-table PostgreSQL schema covering hurricanes, earthquakes, droughts, tsunamis, and floods. SQLModel ORM with analytics endpoints surfacing damage leaders, category breakdowns, yearly trends, and magnitude distributions.',
      highlights: [
        'Normalized PostgreSQL schema: locations, disaster_events, impacts, plus 4 event-type detail tables',
        'FastAPI CRUD API: POST/GET/DELETE /api/events with event-type, year, and country filters + pagination',
        'Analytics: /summary, /by-type, /yearly-trend, /top-deadly, /damage-leaders, /hurricane-categories, /earthquake-magnitudes',
        '20 pytest tests with SQLite in-memory DB; fixture-based test isolation via conftest seed helpers',
        'Docker Compose: PostgreSQL 16 with health-check gated startup + auto schema init from SQL DDL files',
      ],
      tags: ['FastAPI', 'PostgreSQL', 'SQLModel', 'SQLAlchemy', 'Python', 'Docker', 'REST APIs', 'Analytics'],
      github: 'https://github.com/guduruharshita/Storm-Hurricane-Rainfall-Flooding-Database',
    },
  ],

  skills: {
    'Frontend':     { pct: 90, items: ['React 18', 'TypeScript', 'Vite', 'Tailwind CSS', 'JavaScript ES6+', 'HTML5/CSS3'] },
    'Backend':      { pct: 85, items: ['FastAPI', 'Java', 'Spring Boot', 'Node.js', 'JWT', 'RBAC', 'REST APIs'] },
    'Databases':    { pct: 82, items: ['PostgreSQL', 'SQLModel', 'SQLAlchemy', 'MySQL', 'MongoDB', 'SQLite', 'Redis'] },
    'ML / AI':      { pct: 88, items: ['TensorFlow', 'Keras', 'PyTorch', 'XGBoost', 'Scikit-learn', 'Prophet', 'NumPy', 'Pandas'] },
    'Blockchain':   { pct: 75, items: ['Solidity', 'OpenZeppelin', 'Hardhat', 'ethers.js v6', 'EIP-191', 'MetaMask', 'Ethereum'] },
    'Tools & Cloud':{ pct: 83, items: ['Docker', 'GitHub Actions', 'Git', 'AWS basics', 'Power BI', 'Tableau', 'Agile/JIRA'] },
  },

  languages: ['Python', 'TypeScript', 'JavaScript', 'Java', 'Solidity', 'SQL', 'C', 'C++'],

  publications: [
    {
      title: 'Earthquake Prediction and Synthetic Seismogram Generation Using Hybrid CNN-LSTM Model',
      journal: 'American Journal of Civil Engineering — Vol. 13, Issue 5, October 2025',
      date: 'Oct 2025',
      tags: ['Deep Learning', 'CNN-LSTM', 'Seismology', 'TensorFlow', 'Peer Reviewed'],
      url: 'https://www.sciencepg.com/article/10.11648/j.ajce.20251305.14',
    },
    {
      title: 'Design and Analysis of Cyber Security Infrastructure in Large Enterprises',
      journal: 'International Journal of All Research Education and Scientific Methods (IJARESM) — April 2023',
      date: 'Apr 2023',
      tags: ['Cyber Security', 'Enterprise Architecture', 'Infrastructure', 'Research'],
      url: 'https://www.ijaresm.com/uploaded_files/document_file/Darshan_Joshi9Suj.pdf',
    },
  ],
}
