export const PROFILE = {
  name: 'Harshita Guduru',
  title: 'Full-Stack Engineer & ML Researcher',
  tagline: 'Software engineer with expertise in full-stack development, machine learning, and blockchain — with a published research record in deep learning.',
  location: 'Southfield, Michigan, USA',

  contact: {
    email: 'guduruharshita2001@gmail.com',
    phone: '947.240.5093',
    linkedin: 'https://linkedin.com/in/guduruharshita',
    linkedinLabel: 'linkedin.com/in/guduruharshita',
    github: 'https://github.com/guduruharshita',
    githubLabel: 'github.com/guduruharshita',
  },

  experience: [
    {
      role: 'Graduate Research Assistant',
      company: 'Lawrence Technological University',
      location: 'Southfield, MI',
      period: 'Dec 2024 – Present',
      type: 'Research',
      bullets: [
        'Designed and trained a hybrid CNN-LSTM deep learning model for seismic event prediction and synthetic seismogram generation across 10,000+ seismic records.',
        'Achieved 84% classification accuracy — published in the American Journal of Civil Engineering, October 2025.',
        'Developed Python data pipelines using NumPy and Pandas for preprocessing large-scale seismic datasets.',
        'Collaborated with civil engineering faculty to bridge ML research with structural safety applications.',
      ],
      tags: ['TensorFlow', 'Keras', 'CNN-LSTM', 'Python', 'NumPy', 'Pandas', 'Deep Learning'],
    },
    {
      role: 'Associate Software Engineer',
      company: 'Genesis Tech Solutions',
      location: 'Hyderabad, India',
      period: 'May 2023 – Nov 2023',
      type: 'Full-Time',
      bullets: [
        'Built and shipped a full-stack e-learning platform using React.js and Spring Boot serving 1,000+ active users.',
        'Reduced page load time by 30% through component-level code splitting, lazy loading, and API response caching.',
        'Implemented JWT-based authentication with role-based access control (RBAC) for student, instructor, and admin roles.',
        'Designed and managed PostgreSQL schema including user management, course content, and progress tracking tables.',
      ],
      tags: ['React.js', 'Spring Boot', 'PostgreSQL', 'JWT', 'RBAC', 'Java', 'REST APIs'],
    },
  ],

  education: [
    {
      degree: 'M.S. Computer Science',
      school: 'Lawrence Technological University',
      location: 'Southfield, MI',
      period: 'Jan 2024 – May 2026',
      courses: ['Machine Learning', 'Deep Learning', 'Distributed Systems', 'Cloud Computing', 'Data Mining', 'Algorithms'],
    },
    {
      degree: 'B.Tech Computer Science',
      school: 'JNTU Hyderabad',
      location: 'Hyderabad, India',
      period: 'Sep 2019 – May 2023',
      courses: ['Data Structures', 'OOP', 'DBMS', 'Computer Networks', 'Cyber Security', 'Web Development'],
    },
  ],

  projects: [
    {
      title: 'DiscoveryAI',
      subtitle: 'AI-Powered Project Discovery Platform',
      category: 'Full-Stack',
      icon: '🤖',
      period: '2024',
      description: 'An intelligent platform that leverages OpenAI to help users discover, organize and explore software projects through natural language queries. Features real-time AI responses, MongoDB persistence, and a clean React frontend.',
      highlights: [
        'Integrated OpenAI API for natural language project search and intelligent recommendations',
        'Built FastAPI backend with async endpoints for real-time AI response streaming',
        'Designed MongoDB document schema for flexible project metadata storage',
        'Created responsive React UI with dynamic filtering and search capabilities',
        'Implemented user session management and query history persistence',
      ],
      tags: ['FastAPI', 'React', 'OpenAI API', 'MongoDB', 'Python', 'TypeScript', 'REST APIs'],
      github: 'https://github.com/guduruharshita/Digital-Project-Discovery-AI-Platform',
    },
    {
      title: 'AuthChain',
      subtitle: 'Blockchain-Based Authentication System',
      category: 'Blockchain',
      icon: '🔐',
      period: '2024',
      description: 'A decentralized authentication system built on Ethereum using Solidity smart contracts. Eliminates single points of failure in traditional auth systems by storing credentials and access logs on-chain.',
      highlights: [
        'Wrote and deployed Solidity smart contracts on Ethereum for credential storage and verification',
        'Integrated MetaMask wallet for user identity and Web3.js for frontend blockchain interaction',
        'Used Ganache for local blockchain testing and Truffle for contract deployment pipeline',
        'Built Node.js backend to bridge smart contract calls with the web application',
        'Reduced authentication attack surface by removing centralized credential databases',
      ],
      tags: ['Solidity', 'Ethereum', 'Web3.js', 'Node.js', 'MetaMask', 'Ganache', 'Ethers.js'],
      github: 'https://github.com/guduruharshita/Blockchain-base-Authentication-System',
    },
    {
      title: 'CNN-LSTM Seismic Research',
      subtitle: 'Hybrid Deep Learning for Earthquake Prediction',
      category: 'ML Research',
      icon: '🌍',
      period: '2024 – 2025',
      description: 'Published research developing a hybrid CNN-LSTM architecture for earthquake prediction and synthetic seismogram generation. Trained on 10,000+ seismic records with 84% classification accuracy.',
      highlights: [
        'Designed hybrid CNN-LSTM model combining convolutional spatial feature extraction with LSTM temporal modelling',
        'Processed and cleaned 10,000+ real seismic records using custom NumPy/Pandas pipelines',
        'Achieved 84% accuracy in earthquake event classification — outperforming baseline LSTM-only models',
        'Generated synthetic seismograms to augment training data and improve model generalization',
        'Published in American Journal of Civil Engineering, Volume 13, Issue 5, October 2025',
      ],
      tags: ['TensorFlow', 'Keras', 'CNN-LSTM', 'Python', 'NumPy', 'Pandas', 'Deep Learning', 'Seismology'],
      github: 'https://github.com/guduruharshita/Earthquake-Prediction-and-Synthetic-Seismogram-Generation-Using-Hybrid-CNN-LSTM-Model',
      publication: 'https://www.sciencepg.com/article/10.11648/j.ajce.20251305.14',
    },
    {
      title: 'Twitter/X Analytics Engine',
      subtitle: 'Social Media Engagement Prediction with ML',
      category: 'ML',
      icon: '📊',
      period: '2024',
      description: 'Multi-model machine learning system analyzing 100,000+ tweets to predict engagement metrics. Combines gradient boosting, OLS regression, time-series forecasting and PyTorch neural networks.',
      highlights: [
        'Collected and processed 100,000+ tweets using Twitter API with custom data cleaning pipelines',
        'Trained XGBoost model achieving R²=0.777 for engagement score prediction',
        'Built OLS regression baseline achieving R²=0.852 for tweet reach estimation',
        'Implemented Facebook Prophet for time-series forecasting of trending topic cycles',
        'Developed PyTorch neural network for sentiment-aware engagement classification',
        'Visualized insights with interactive Matplotlib dashboards',
      ],
      tags: ['XGBoost', 'PyTorch', 'Prophet', 'OLS', 'Python', 'Scikit-learn', 'Pandas', 'Matplotlib'],
      github: 'https://github.com/guduruharshita',
    },
    {
      title: 'Graph Traversal Analyzer',
      subtitle: 'BFS/DFS Algorithm Visualization Tool',
      category: 'Algorithms',
      icon: '🕸️',
      period: '2023',
      description: 'An interactive tool for visualizing and comparing BFS and DFS graph traversal algorithms on custom graphs. Built with NetworkX for graph operations and Matplotlib for real-time step-by-step animation.',
      highlights: [
        'Implemented BFS and DFS algorithms from scratch with step-by-step traversal state tracking',
        'Built interactive graph builder allowing custom node/edge creation and weighted connections',
        'Used NetworkX for graph data structures and efficient adjacency representation',
        'Animated traversal order with color-coded node states (unvisited, visiting, visited)',
        'Added performance comparison metrics: time complexity, nodes visited, path length',
      ],
      tags: ['Python', 'NetworkX', 'Matplotlib', 'BFS', 'DFS', 'Graph Theory', 'Algorithms'],
      github: 'https://github.com/guduruharshita/Graph-traversal-Algorithm',
    },
    {
      title: 'Storm Events Database',
      subtitle: 'Weather Data ETL & Analytics Platform',
      category: 'Full-Stack',
      icon: '🌩️',
      period: '2023',
      description: 'End-to-end data engineering project ingesting NOAA storm event datasets into a normalized MySQL database with a full ETL pipeline, query optimization, and analytics dashboard.',
      highlights: [
        'Built ETL pipeline to ingest and normalize NOAA storm/hurricane/flood datasets into MySQL',
        'Designed normalized relational schema with 8+ tables covering events, locations, and damage metrics',
        'Wrote optimized SQL queries with indexes reducing complex aggregation query time by 60%',
        'Created Python scripts for automated data cleaning, deduplication, and validation',
        'Built analytics layer for damage trend analysis, regional risk scoring, and event frequency reporting',
      ],
      tags: ['MySQL', 'Python', 'ETL', 'SQLite', 'NOAA', 'Data Engineering', 'SQL', 'Pandas'],
      github: 'https://github.com/guduruharshita/Storm-Hurricane-Rainfall-Flooding-Database',
    },
  ],

  skills: {
    'Frontend':     { pct: 90, items: ['React.js', 'JavaScript ES6+', 'TypeScript', 'HTML5', 'CSS3', 'Bootstrap', 'REST APIs'] },
    'Backend':      { pct: 85, items: ['Java', 'Spring Boot', 'Node.js', 'FastAPI', 'JWT', 'RBAC', 'Microservices'] },
    'Databases':    { pct: 82, items: ['PostgreSQL', 'MySQL', 'MongoDB', 'SQLite', 'Oracle SQL', 'Redis'] },
    'ML / AI':      { pct: 88, items: ['TensorFlow', 'Keras', 'PyTorch', 'XGBoost', 'Scikit-learn', 'Prophet', 'NumPy', 'Pandas'] },
    'Blockchain':   { pct: 75, items: ['Solidity', 'Ethereum', 'MetaMask', 'Ganache', 'Web3.js', 'Ethers.js', 'Truffle'] },
    'Tools & Cloud':{ pct: 83, items: ['Git/GitHub', 'Power BI', 'Tableau', 'VS Code', 'JIRA', 'Agile', 'AWS basics'] },
  },

  languages: ['Java', 'Python', 'JavaScript', 'TypeScript', 'C', 'C++', 'SQL', 'Solidity'],

  publications: [
    {
      title: 'Earthquake Prediction and Synthetic Seismogram Generation Using Hybrid CNN-LSTM Model',
      journal: 'American Journal of Civil Engineering — Vol. 13, Issue 5, October 2025',
      date: 'Oct 2025',
      tags: ['Deep Learning', 'CNN-LSTM', 'Seismology', 'TensorFlow', 'Peer Reviewed'],
      url: 'https://www.sciencepg.com/article/10.11648/j.ajce.20251305.14',
    },
    {
      title: 'Design and Analysis of Cyber Security Infrastructure in Large Enterprises',
      journal: 'International Journal of All Research Education and Scientific Methods (IJARESM) — April 2023',
      date: 'Apr 2023',
      tags: ['Cyber Security', 'Enterprise Architecture', 'Infrastructure', 'Research'],
      url: 'https://www.ijaresm.com/uploaded_files/document_file/Darshan_Joshi9Suj.pdf',
    },
  ],
}
